# Generated by Django 5.0.3 on 2024-05-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
