# Generated by Django 5.0.3 on 2024-05-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='SelectedDateTime',
        ),
    ]
