# Generated by Django 5.0.3 on 2024-05-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_todolist_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_task',
            field=models.BooleanField(default=False),
        ),
    ]
