# Generated by Django 5.0.3 on 2024-05-07 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_is_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_task',
            new_name='completed',
        ),
    ]
