# Generated by Django 5.0.3 on 2024-05-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='WishlistItem',
        ),
    ]
