# Generated by Django 5.0.3 on 2024-05-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_category_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='product',
        ),
    ]
